// 刀剣専覧関連
export const twitterURL: string = 'https://twitter.com/TohkenBrowser';

// 刀剣乱舞側設定
export const gameURL: string = 'http://pc-play.games.dmm.com/play/tohken/';
export const gameTitle: string = `刀剣専覧 ${chrome.runtime.getManifest().version} -刀剣乱舞専用ブラウザ-`;
export const gameSize: any = { width: 1030, height: 580 };
export const gameRatio: number = gameSize.height / gameSize.width;

// 表示系設定
export const headerMenuHeight: number = 65;
export const statusViewHeight: number = 300;

// ゲーム内定数
export const partyNo = 4;
export const partyMemberNo = 6;
export const forgeNo = 4;
export const repairNo = 4;

export const statusLabel = {
    none: '',
    hp: '生存',
    atk: '打撃',
    def: '統率',
    mobile: '機動',
    back: '衝力',
    scout: '偵察',
    hide: '隠蔽',
    loyalties: '必殺',
    fatigue: '英気',
    amulet: '御守',
};

export const forgeColorName = {
    20: 'navy',
    25: 'darkgreen',
    30: 'olive',
    40: 'limegreen',
    90: 'greenyellow',
    150: 'chartreuse',
    180: 'goldenrod',
    200: 'gold',
    240: 'crimson',
    300: 'red',
    360: 'ghostwhite',
    601: 'purple',
};


export const equipStatus = {
    0: {
        name: '不明',
        soldier: 0,
        atk: 0,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    1: {
        name: '投石兵・並',
        soldier: 8,
        atk: 0,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 1,
        hide: 1,
    },
    2: {
        name: '投石兵・上',
        soldier: 9,
        atk: 0,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 2,
        hide: 2,
    },
    3: {
        name: '投石兵・特上',
        soldier: 10,
        atk: 0,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 3,
        hide: 3,
    },
    4: {
        name: '槍兵・並',
        soldier: 7,
        atk: 0,
        def: 0,
        mobile: 1,
        back: 2,
        scout: 0,
        hide: 0,
    },
    5:
    {
        name: '槍兵・上',
        soldier: 7,
        atk: 0,
        def: 0,
        mobile: 2,
        back: 3,
        scout: 0,
        hide: 0,
    },
    6: {
        name: '槍兵・特上',
        soldier: 8,
        atk: 0,
        def: 0,
        mobile: 3,
        back: 5,
        scout: 0,
        hide: 0,
    },
    7: {
        name: '軽歩兵・並',
        soldier: 8,
        atk: 0,
        def: 0,
        mobile: 2,
        back: 0,
        scout: 0,
        hide: 1,
    },
    8: {
        name: '軽歩兵・上',
        soldier: 9,
        atk: 0,
        def: 0,
        mobile: 2,
        back: 0,
        scout: 0,
        hide: 2,
    },
    9: {
        name: '軽歩兵・特上',
        soldier: 10,
        atk: 0,
        def: 0,
        mobile: 5,
        back: 0,
        scout: 0,
        hide: 3,
    },
    10: {
        name: '重歩兵・並',
        soldier: 10,
        atk: 1,
        def: 2,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    11: {
        name: '重歩兵・上',
        soldier: 11,
        atk: 2,
        def: 2,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    12: {
        name: '重歩兵・特上',
        soldier: 12,
        atk: 3,
        def: 5,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    13: {
        name: '盾兵・並',
        soldier: 11,
        atk: 0,
        def: 5,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    14: {
        name: '盾兵・上',
        soldier: 13,
        atk: 0,
        def: 7,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    15: {
        name: '盾兵・特上',
        soldier: 15,
        atk: 0,
        def: 10,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    16: {
        name: '軽騎兵・並',
        soldier: 9,
        atk: 1,
        def: 0,
        mobile: 2,
        back: 0,
        scout: 0,
        hide: 0,
    },
    17: {
        name: '軽騎兵・上',
        soldier: 10,
        atk: 2,
        def: 1,
        mobile: 3,
        back: 0,
        scout: 0,
        hide: 0,
    },
    18: {
        name: '軽騎兵・特上',
        soldier: 12,
        atk: 3,
        def: 3,
        mobile: 5,
        back: 0,
        scout: 0,
        hide: 0,
    },
    19: {
        name: '重騎兵・並',
        soldier: 11,
        atk: 1,
        def: 3,
        mobile: 0,
        back: 1,
        scout: 0,
        hide: 0,
    },
    20: {
        name: '重騎兵・上',
        soldier: 12,
        atk: 2,
        def: 3,
        mobile: 1,
        back: 2,
        scout: 0,
        hide: 0,
    },
    21: {
        name: '重騎兵・特上',
        soldier: 13,
        atk: 3,
        def: 5,
        mobile: 3,
        back: 3,
        scout: 0,
        hide: 0,
    },
    22: {
        name: '精鋭兵・並',
        soldier: 11,
        atk: 0,
        def: 2,
        mobile: 2,
        back: 0,
        scout: 1,
        hide: 1,
    },
    23: {
        name: '精鋭兵・上',
        soldier: 12,
        atk: 0,
        def: 3,
        mobile: 3,
        back: 0,
        scout: 2,
        hide: 2,
    },
    24: {
        name: '精鋭兵・特上',
        soldier: 13,
        atk: 0,
        def: 5,
        mobile: 5,
        back: 0,
        scout: 3,
        hide: 3,
    },
    25: {
        name: '弓兵・並',
        soldier: 6,
        atk: 0,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 2,
    },
    26: {
        name: '弓兵・上',
        soldier: 7,
        atk: 1,
        def: 0,
        mobile: 0,
        back: 1,
        scout: 0,
        hide: 3,
    },
    27: {
        name: '弓兵・特上',
        soldier: 8,
        atk: 3,
        def: 0,
        mobile: 0,
        back: 3,
        scout: 0,
        hide: 5,
    },
    28: {
        name: '銃兵・並',
        soldier: 5,
        atk: 0,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 2,
        hide: 0,
    },
    29: {
        name: '銃兵・上',
        soldier: 6,
        atk: 1,
        def: 0,
        mobile: 0,
        back: 1,
        scout: 3,
        hide: 0,
    },
    30: {
        name: '銃兵・特上',
        soldier: 6,
        atk: 3,
        def: 0,
        mobile: 0,
        back: 3,
        scout: 5,
        hide: 0,
    },
    31: {
        name: '投豆兵・並',
        soldier: 8,
        atk: 2,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 1,
        hide: 1,
    },
    32: {
        name: '投豆兵・上',
        soldier: 9,
        atk: 3,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 2,
        hide: 2,
    },
    33: {
        name: '投豆兵・特上',
        soldier: 12,
        atk: 6,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 3,
        hide: 3,
    },
    10001: {
        name: '01王庭',
        soldier: 0,
        atk: 3,
        def: 0,
        mobile: 7,
        back: 0,
        scout: 0,
        hide: 0,
    },
    10002: {
        name: '02三国黒',
        soldier: 0,
        atk: 0,
        def: 3,
        mobile: 10,
        back: 3,
        scout: 0,
        hide: 0,
    },
    10003: {
        name: '03松風',
        soldier: 0,
        atk: 2,
        def: 2,
        mobile: 13,
        back: 0,
        scout: 0,
        hide: 0,
    },
    10004: {
        name: '04小雲雀',
        soldier: 0,
        atk: 0,
        def: 2,
        mobile: 17,
        back: 0,
        scout: 2,
        hide: 2,
    },
    10005: {
        name: '05高盾黒',
        soldier: 0,
        atk: 0,
        def: 0,
        mobile: 13,
        back: 3,
        scout: 0,
        hide: 0,
    },
    10006: {
        name: '06花柑子',
        soldier: 0,
        atk: 0,
        def: 3,
        mobile: 15,
        back: 0,
        scout: 0,
        hide: 0,
    },
    10007: {
        name: '07青海波',
        soldier: 0,
        atk: 0,
        def: 0,
        mobile: 13,
        back: 0,
        scout: 3,
        hide: 2,
    },
    10008: {
        name: '08望月',
        soldier: 0,
        atk: 3,
        def: 0,
        mobile: 17,
        back: 0,
        scout: 0,
        hide: 2,
    },
    11011: {
        name: '白毛',
        soldier: 0,
        atk: 0,
        def: 0,
        mobile: 5,
        back: 0,
        scout: 0,
        hide: 0,
    },
    11021: {
        name: '鹿毛',
        soldier: 0,
        atk: 3,
        def: 0,
        mobile: 2,
        back: 0,
        scout: 0,
        hide: 0,
    },
    11031: {
        name: '青毛',
        soldier: 0,
        atk: 5,
        def: 0,
        mobile: 0,
        back: 0,
        scout: 0,
        hide: 0,
    },
    11041: {
        name: '祝一号',
        soldier: 0,
        atk: 2,
        def: 2,
        mobile: 2,
        back: 2,
        scout: 2,
        hide: 2,
    },
    11042: {
        name: '祝一号',
        soldier: 0,
        atk: 2,
        def: 2,
        mobile: 2,
        back: 2,
        scout: 2,
        hide: 2,
    },
    11043: {
        name: '祝三号',
        soldier: 0,
        atk: 2,
        def: 2,
        mobile: 2,
        back: 2,
        scout: 2,
        hide: 2,
    },
    11044: {
        name: '祝四号',
        soldier: 0,
        atk: 2,
        def: 2,
        mobile: 2,
        back: 2,
        scout: 2,
        hide: 2,
    },
};

export const swordName = {
    0: '不明',
    3: '三日月宗近',
    4: '三日月宗近・極',
    5: '小狐丸',
    6: '小狐丸・極',
    7: '石切丸',
    8: '石切丸・極',
    9: '岩融',
    10: '岩融・極',
    11: '今剣',
    12: '今剣・極',
    13: '大典太光世',
    14: '大典太光世・極',
    15: 'ソハヤノツルキ',
    16: 'ソハヤノツルキ・極',
    17: '数珠丸恒次',
    18: '数珠丸恒次・極',
    19: 'にっかり青江',
    20: 'にっかり青江・極',
    23: '鳴狐',
    24: '鳴狐・極',
    25: '一期一振',
    26: '一期一振・極',
    27: '鯰尾藤四郎',
    28: '鯰尾藤四郎・極',
    29: '骨喰藤四郎',
    30: '骨喰藤四郎・極',
    31: '平野藤四郎',
    32: '平野藤四郎・極 ',
    33: '厚藤四郎',
    34: '厚藤四郎・極 ',
    35: '後藤藤四郎',
    36: '後藤藤四郎・極',
    37: '信濃藤四郎',
    38: '信濃藤四郎・極',
    39: '前田藤四郎',
    40: '前田藤四郎・極',
    41: '秋田藤四郎',
    42: '秋田藤四郎・極',
    43: '博多藤四郎',
    44: '博多藤四郎・極',
    45: '乱藤四郎',
    46: '乱藤四郎・極',
    47: '五虎退',
    48: '五虎退・極',
    49: '薬研藤四郎',
    50: '薬研藤四郎・極',
    51: '包丁藤四郎',
    52: '包丁藤四郎・極',
    53: '大包平',
    54: '大包平・極',
    55: '鶯丸',
    56: '鶯丸・極',
    57: '明石国行',
    58: '明石国行・極',
    59: '蛍丸',
    60: '蛍丸・極',
    61: '愛染国俊',
    62: '愛染国俊・極',
    63: '千子村正',
    64: '千子村正・極',
    65: '蜻蛉切',
    66: '蜻蛉切・極',
    67: '物吉貞宗',
    68: '物吉貞宗・極',
    69: '太鼓鐘貞宗',
    70: '太鼓鐘貞宗・極',
    71: '亀甲貞宗',
    72: '亀甲貞宗・極',
    73: '燭台切光忠',
    74: '燭台切光忠・極',
    75: '大般若長光',
    76: '大般若長光・極',
    77: '小竜景光',
    78: '小竜景光・極',
    79: '江雪左文字',
    80: '江雪左文字・極',
    81: '宗三左文字',
    82: '宗三左文字・極',
    83: '小夜左文字',
    84: '小夜左文字・極',
    85: '加州清光',
    86: '加州清光・極',
    87: '大和守安定',
    88: '大和守安定・極',
    89: '歌仙兼定',
    90: '歌仙兼定・極',
    91: '和泉守兼定',
    92: '和泉守兼定・極',
    93: '陸奥守吉行',
    94: '陸奥守吉行・極',
    95: '山姥切国広',
    96: '山姥切国広・極',
    97: '山伏国広',
    98: '山伏国広・極',
    99: '堀川国広',
    100: '堀川国広・極',
    101: '蜂須賀虎徹',
    102: '蜂須賀虎徹・極',
    103: '浦島虎徹',
    104: '浦島虎徹・極',
    105: '長曽祢虎徹',
    106: '長曽祢虎徹・極',
    107: '髭切',
    108: '髭切・特一',
    109: '髭切・特二',
    110: '髭切・特三',
    111: '髭切・極',
    112: '膝丸',
    113: '膝丸・特一',
    114: '膝丸・特二',
    115: '膝丸・極',
    116: '大倶利伽羅',
    117: '大倶利伽羅・極',
    118: 'へし切長谷部',
    119: 'へし切長谷部・極',
    120: '不動行光',
    121: '不動行光・極',
    122: '獅子王',
    123: '獅子王・極',
    124: '小烏丸',
    125: '小烏丸・極',
    128: '同田貫正国',
    129: '同田貫正国・極',
    130: '鶴丸国永',
    131: '鶴丸国永・極',
    132: '太郎太刀',
    133: '太郎太刀・極',
    134: '次郎太刀',
    135: '次郎太刀・極',
    136: '日本号',
    137: '日本号・極',
    138: '御手杵',
    139: '御手杵・極',
    140: '巴形薙刀',
    141: '巴形薙刀・極',
    142: '毛利藤四郎',
    143: '毛利藤四郎・極',
    144: '篭手切江',
    145: '篭手切江・極',
    146: '謙信景光',
    147: '謙信景光・極',
    148: '小豆長光',
    149: '小豆長光・極',
    150: '日向正宗',
    151: '日向正宗・極',
    152: '静形薙刀',
    153: '静形薙刀・極',
    154: '南泉一文字',
    155: '南泉一文字・極',
    156: '千代金丸',
    157: '千代金丸・極',
    158: '山姥切長義',
    159: '山姥切長義・極',
    160: '豊前江',
    161: '豊前江・極',
    162: '祢々切丸',
    163: '祢々切丸・極',
    164: '白山吉光',
    165: '白山吉光・極',
    166: '南海太郎朝尊',
    167: '南海太郎朝尊・極',
    168: '肥前忠広',
    169: '肥前忠広・極',
    170: '北谷菜切',
    171: '北谷菜切・極',
    172: '桑名江',
    173: '桑名江・極',
    174: '水心子正秀',
    175: '水心子正秀・極',
    176: '源清麿',
    177: '源清麿・極',
};
